### ISSUE TITLE
discopop_wizard failed to start on Mac OS

### ISSUE THREAD

**Issue by LChenGit** [discopop-project/discopop#326] opened 2023-03-08 22:29 UTC
discopop_wizard failed to start on my MacBook with a apple silicon cpu. With the same enviroment setup, it works fine on my ubuntu machine.

error message:
starting DiscoPoP Wizard...

Traceback (most recent call last):
  File "/Users/lc/opt/anaconda3/envs/pg/bin/discopop_wizard", line 8, in <module>
    sys.exit(main())
  File "/Users/lc/opt/anaconda3/envs/pg/lib/python3.10/site-packages/discopop_wizard/__main__.py", line 30, in main
    wizard_main(convert_args(args))
  File "/Users/lc/opt/anaconda3/envs/pg/lib/python3.10/site-packages/discopop_wizard/wizard.py", line 43, in main
    wizard = DiscoPoPConfigurationWizard(config_dir, arguments)
  File "/Users/lc/opt/anaconda3/envs/pg/lib/python3.10/site-packages/discopop_wizard/wizard.py", line 87, in __init__
    self.initialize_screen(config_dir)
  File "/Users/lc/opt/anaconda3/envs/pg/lib/python3.10/site-packages/discopop_wizard/wizard.py", line 99, in initialize_screen
    self.window.attributes('-zoomed', True)
  File "/Users/lc/opt/anaconda3/envs/pg/lib/python3.10/tkinter/__init__.py", line 2005, in wm_attributes
    return self.tk.call(args)
_tkinter.TclError: bad attribute "-zoomed": must be -alpha, -fullscreen, -modified, -notify, -titlepath, -topmost, -transparent, or -type

**Comment by lukasrothenberger** [comment] 2023-03-09 12:06
Hi @LChenGit,

could you please check if the issue still persists on the latest state of the `master` branch?
Unfortunately, we do not have a machine running MacOS at the moment, so testing and reproducing the issue is not possible for us.

**Comment by LChenGit** [comment] 2023-03-09 17:50
Hi @lukasrothenberger ,

I am happy to help with testing on MacOS. I rebuilt DiscoPoP from source code and it works fine. One thing I noticed is that during the build process, it notified me my environment does not have the "tinter" module.
`ModuleNotFoundError: No module named '_tkinter'`
`CMake Error at CMakeLists.txt:65 (message): Python module 'tkinter' not found.  Please install the 'python3-tk' package
  via a package manager.`
It is the same environment I run `discopop_wizard` after installing through pip: `pip install discopop`. After manually install python-tk by: `brew install python-tk` everything looks fine. 
I think it is fine to close this issue. If you need any help with testing in the future, feel free to let me know:) Thank you!

**Comment by lukasrothenberger** [comment] 2023-03-10 09:26
Hi @LChenGit;
thank you very much for your feedback!

Unfortunately it seems impossible to install all required parts of tkinter using pip alone during the build (hence the build-time check and the `ModuleNotFoundError`).

> The problem still exists with the pip version discopop_wizard.

This will be fixed in the next release (Version 2.2.0), which will happen later today or in the beginning of next week at the latest.

Best,
Lukas

**Comment by lukasrothenberger** [comment] 2023-03-14 12:10
Hi @LChenGit;

> The problem still exists with the pip version discopop_wizard.

Does the issue still persist with version 2.2.0?
If not, i would go ahead and close the issue.

Best,
Lukas

**Comment by LChenGit** [comment] 2023-03-14 16:06
Hi @lukasrothenberger,

It works fine with the latest version. Thank you for the updating. I think it is fine to close this issue.

**Closed** 2023-03-17 15:17 UTC
